/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decryptRust(hexData: string, keyStr: string): string

export declare function encryptRust(data: string, keyStr: string): string
